[package]
name = "pinmame-nvram"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
include_dir = "0.7.4"

[dev-dependencies]
pretty_assertions = "1.4.1"
testdir = "0.9.1"
